# Generated by Django 4.2.24 on 2025-09-19 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_client_province_remove_settings_province_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='clientLogo',
            new_name='companyLogo',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='clientName',
            new_name='companyName',
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro')], max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='invoice.settings')),
            ],
        ),
    ]
